name: simple_dxf
description: Generate DXF content in ASCII format which can be written to a File.

publish_to: none

version: 0.0.1

environment:
  sdk: ^3.1.0

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
